# \u670D\u52A1\u5668\u7AEF\u53E3\u53F7
server:
  port: 8090

# \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456

# \u6574\u5408mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
