server:
  port: 9000
spring:
  application:
    name: demo-lucene
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/es?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456

# mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true