spring:
  profiles:
    active: prd
#debug: true
#logging:
#  level:
#    root: info
#  file: /Users/prim/java/java-workspace/Awesome-Java-Notebook.log
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oa
#    username: root
#    password: root
#
#mall:
#  config:
#    name: 爱美商城
#    description: 这是一家化妆品特卖网站
#    hot-sales: 20
#    show-advert: true